project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
    - "!slides.Rmd"

website:
  title: "An Introduction to R"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/itsleeds/intro-to-R
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://github.com/itsleeds/intro-to-R/discussions
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
